receivers:
    otlp:
        protocols:
            http:
                endpoint: "0.0.0.0:4318"
            grpc:
                endpoint: "0.0.0.0:4317"

processors:
    batch:
        timeout: 1s
        send_batch_size: 1024

exporters:
    logging:
        verbosity: detailed
    otlp:
        endpoint: "jaeger:4317"
        tls:
            insecure: true

extensions:
    health_check:
    pprof:
    zpages:
        endpoint: "0.0.0.0:55679"

service:
    extensions: [health_check, pprof, zpages]
    pipelines:
        traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [logging, otlp]
        metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [logging]
        logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [logging]
