version: "3.8"

services:
    # Search Engine
    weaviate:
        image: semitechnologies/weaviate:1.24.1
        ports:
            - "8081:8080"
        environment:
            QUERY_DEFAULTS_LIMIT: 25
            AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
            DEFAULT_VECTORIZER_MODULE: "text2vec-transformers"
            ENABLE_MODULES: "text2vec-transformers"
            TRANSFORMERS_INFERENCE_API: "http://t2v-transformer:8080"
        volumes:
            - weaviate_data:/var/lib/weaviate
        depends_on:
            - t2v-transformer

    t2v-transformer:
        image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
        environment:
            ENABLE_CUDA: "0"

    # Storage
    seaweedfs-master:
        image: chrislusf/seaweedfs:3.62
        ports:
            - "9333:9333"
            - "19333:19333"
        command: "master -ip=seaweedfs-master"
        volumes:
            - seaweedfs_data:/data

    seaweedfs-volume:
        image: chrislusf/seaweedfs:3.62
        ports:
            - "8080:8080"
        command: 'volume -mserver="seaweedfs-master:9333" -port=8080'
        volumes:
            - seaweedfs_data:/data
        depends_on:
            - seaweedfs-master

    # Observability
    otel-collector:
        image: otel/opentelemetry-collector:0.96.0
        command: ["--config=/etc/otel-collector-config.yaml"]
        volumes:
            - ./infra/otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml
        ports:
            - "4318:4318" # OTLP HTTP
            - "4317:4317" # OTLP gRPC
            - "55679:55679" # zpages extension

volumes:
    weaviate_data:
    seaweedfs_data:
